# Generated by Django 5.0.3 on 2024-04-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Age',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
